version: '3.9'

# Global environment variables
x-environment: &shared-environment
  LOCAL_FILES_PATH: /usr/src/app/local_files
  HOST_FILES_PATH: ${LOCAL_FILES_PATH}
  EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
  EMBEDDING_SIZE: ${EMBEDDING_SIZE}
  START_INDEXING: ${START_INDEXING}
  CONTAINER_PATH: /usr/src/app/local_files
  QDRANT_HOST: qdrant
  QDRANT_PORT: 6333
  PYTHONPATH: /usr/src
  PYTHONUNBUFFERED: 'TRUE'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - F:/qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"
      <<: *shared-environment

  indexer:
    build: 
      context: ./indexer
      dockerfile: Dockerfile
      args:
        EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
        EMBEDDING_SIZE: ${EMBEDDING_SIZE}
        START_INDEXING: ${START_INDEXING}
        RERANKER_MODEL: ${RERANKER_MODEL}
        CHUNK_SIZE: ${CHUNK_SIZE}
        CHUNK_OVERLAP: ${CHUNK_OVERLAP}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ${LOCAL_FILES_PATH}
        target: /usr/src/app/local_files
      - ./indexer:/usr/src/app
      - ./indexer/.minimaignore:/usr/src/app/local_files/.minimaignore
      - huggingface_cache:/root/.cache/huggingface      
    ports:
      - 8001:8000
    environment: 
      <<: *shared-environment 
    depends_on:
      - qdrant

volumes:
  huggingface_cache: